/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace MezoBanqGiftCard {
      
    export type GiftCardStruct = {id: BigNumberish, creator: AddressLike, claimer: AddressLike, amount: BigNumberish, codeHash: BytesLike, expiresAt: BigNumberish, claimed: boolean, refunded: boolean}

    export type GiftCardStructOutput = [id: bigint, creator: string, claimer: string, amount: bigint, codeHash: string, expiresAt: bigint, claimed: boolean, refunded: boolean] & {id: bigint, creator: string, claimer: string, amount: bigint, codeHash: string, expiresAt: bigint, claimed: boolean, refunded: boolean }
  
    }

  export interface MezoBanqGiftCardInterface extends Interface {
    getFunction(nameOrSignature: "cards" | "checkCode" | "claimCard" | "createCard" | "getCard" | "hashCode" | "musdToken" | "nextCardId" | "owner" | "refundCard" | "totalLockedMusd"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CardClaimed" | "CardCreated" | "CardRefunded"): EventFragment;

    encodeFunctionData(functionFragment: 'cards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkCode', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'claimCard', values: [string]): string;
encodeFunctionData(functionFragment: 'createCard', values: [BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCard', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hashCode', values: [string]): string;
encodeFunctionData(functionFragment: 'musdToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextCardId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundCard', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalLockedMusd', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'cards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkCode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hashCode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'musdToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextCardId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundCard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLockedMusd', data: BytesLike): Result;
  }

  
    export namespace CardClaimedEvent {
      export type InputTuple = [cardId: BigNumberish, claimer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [cardId: bigint, claimer: string, amount: bigint];
      export interface OutputObject {cardId: bigint, claimer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardCreatedEvent {
      export type InputTuple = [cardId: BigNumberish, creator: AddressLike, amount: BigNumberish, expiresAt: BigNumberish];
      export type OutputTuple = [cardId: bigint, creator: string, amount: bigint, expiresAt: bigint];
      export interface OutputObject {cardId: bigint, creator: string, amount: bigint, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CardRefundedEvent {
      export type InputTuple = [cardId: BigNumberish, creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [cardId: bigint, creator: string, amount: bigint];
      export interface OutputObject {cardId: bigint, creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MezoBanqGiftCard extends BaseContract {
    
    connect(runner?: ContractRunner | null): MezoBanqGiftCard;
    waitForDeployment(): Promise<this>;

    interface: MezoBanqGiftCardInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cards: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, bigint, boolean, boolean] & {id: bigint, creator: string, claimer: string, amount: bigint, codeHash: string, expiresAt: bigint, claimed: boolean, refunded: boolean }],
      'view'
    >
    

    
    checkCode: TypedContractMethod<
      [codeHash: BytesLike, ],
      [[boolean, bigint, bigint] & {valid: boolean, cardId: bigint, amount: bigint }],
      'view'
    >
    

    
    claimCard: TypedContractMethod<
      [plainCode: string, ],
      [void],
      'nonpayable'
    >
    

    
    createCard: TypedContractMethod<
      [amount: BigNumberish, codeHash: BytesLike, expiresAt: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getCard: TypedContractMethod<
      [cardId: BigNumberish, ],
      [MezoBanqGiftCard.GiftCardStructOutput],
      'view'
    >
    

    
    hashCode: TypedContractMethod<
      [plainCode: string, ],
      [string],
      'view'
    >
    

    
    musdToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nextCardId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    refundCard: TypedContractMethod<
      [cardId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalLockedMusd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cards'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, bigint, boolean, boolean] & {id: bigint, creator: string, claimer: string, amount: bigint, codeHash: string, expiresAt: bigint, claimed: boolean, refunded: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'checkCode'): TypedContractMethod<
      [codeHash: BytesLike, ],
      [[boolean, bigint, bigint] & {valid: boolean, cardId: bigint, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'claimCard'): TypedContractMethod<
      [plainCode: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createCard'): TypedContractMethod<
      [amount: BigNumberish, codeHash: BytesLike, expiresAt: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCard'): TypedContractMethod<
      [cardId: BigNumberish, ],
      [MezoBanqGiftCard.GiftCardStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hashCode'): TypedContractMethod<
      [plainCode: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'musdToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextCardId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'refundCard'): TypedContractMethod<
      [cardId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalLockedMusd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'CardClaimed'): TypedContractEvent<CardClaimedEvent.InputTuple, CardClaimedEvent.OutputTuple, CardClaimedEvent.OutputObject>;
getEvent(key: 'CardCreated'): TypedContractEvent<CardCreatedEvent.InputTuple, CardCreatedEvent.OutputTuple, CardCreatedEvent.OutputObject>;
getEvent(key: 'CardRefunded'): TypedContractEvent<CardRefundedEvent.InputTuple, CardRefundedEvent.OutputTuple, CardRefundedEvent.OutputObject>;

    filters: {
      
      'CardClaimed(uint256,address,uint256)': TypedContractEvent<CardClaimedEvent.InputTuple, CardClaimedEvent.OutputTuple, CardClaimedEvent.OutputObject>;
      CardClaimed: TypedContractEvent<CardClaimedEvent.InputTuple, CardClaimedEvent.OutputTuple, CardClaimedEvent.OutputObject>;
    

      'CardCreated(uint256,address,uint256,uint256)': TypedContractEvent<CardCreatedEvent.InputTuple, CardCreatedEvent.OutputTuple, CardCreatedEvent.OutputObject>;
      CardCreated: TypedContractEvent<CardCreatedEvent.InputTuple, CardCreatedEvent.OutputTuple, CardCreatedEvent.OutputObject>;
    

      'CardRefunded(uint256,address,uint256)': TypedContractEvent<CardRefundedEvent.InputTuple, CardRefundedEvent.OutputTuple, CardRefundedEvent.OutputObject>;
      CardRefunded: TypedContractEvent<CardRefundedEvent.InputTuple, CardRefundedEvent.OutputTuple, CardRefundedEvent.OutputObject>;
    
    };
  }